artifact_location: file:///C:/Users/adity/Desktop/house-price-prediction/mlflow/0
creation_time: 1743920030869
experiment_id: '0'
last_update_time: 1743920030869
lifecycle_stage: active
name: Default
